export default {
  account: "Account",
  arabic: "AR",
  back: "Back",
  close: "Close",
  dark: "Dark",
  english: "EN",
  home: "Home",
  language: "Language",
  light: "Light",
  new: "New",
  offline: "offline",
  online: "online",
  profile: "Profile",
  search: "Search",
  settings: "Settings",
  signOut: "Sign out",
  theme: "Theme",
  workspace: "Workspace",
  working: "Working...",
} as const;
