export default {
  account: "الحساب",
  arabic: "AR",
  back: "رجوع",
  close: "إغلاق",
  dark: "داكن",
  english: "EN",
  home: "الرئيسية",
  language: "اللغة",
  light: "فاتح",
  new: "جديد",
  offline: "غير متصل",
  online: "متصل",
  profile: "الملف الشخصي",
  search: "البحث",
  settings: "الإعدادات",
  signOut: "تسجيل الخروج",
  theme: "المظهر",
  workspace: "مساحة العمل",
  working: "جارٍ العمل...",
} as const;
